/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export {
	TOKEN_CANVAS_CHART_TYPE,
	TOKEN_CHART,
	TOKEN_CHART_COLORS,
	TOKEN_LINE_TYPE
} from './array';
export { DEFAULT_CANVAS_CHART_PADDING } from './map';
export {
	BAR_CHART_COLOR_SCHEME,
	LINE_CHART_COLOR_SCHEME,
	PRESET_CANVAS_CHART
} from './preset';
export { HEATMAP_GRADIENT_BY_SCHEME } from './record';
